services:
  sveltekit:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-supersecretplaceholder}
        POSTGRES_URL: ${POSTGRES_URL:-postgresql://postgres:password@postgres:5432/sample_manager}
      target: builder
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:5173' # vite dev server port
    command: pnpm dev --host
    environment:
      POSTGRES_URL: ${POSTGRES_URL:-postgresql://postgres:password@postgres:5432/sample_manager}
      ORIGIN: http://localhost:5173
      FASTAPI_URL: http://fastapi:8000

  fastapi:
    build:
      context: ./fast-api
      dockerfile: Dockerfile
    volumes:
      - ./fast-api:/app # live reload your python changes
      - ./uploads:/app/uploads
    ports:
      - '8000:8000'
    environment:
      UPLOAD_DIR: /app/uploads
    command: uvicorn fastapi_server.main:app --host 0.0.0.0 --reload
